import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:image_picker/image_picker.dart';

import '../core/providers.dart';

class LoginScreen extends ConsumerStatefulWidget {
  const LoginScreen({super.key});
  @override ConsumerState<LoginScreen> createState() => _LoginScreenState();
}
class _LoginScreenState extends ConsumerState<LoginScreen> {
  final email = TextEditingController();
  final password = TextEditingController();
  bool loading = false;
  Future<void> submit() async { setState(() => loading = true); try { await ref.read(authRepositoryProvider).signIn(email.text.trim(), password.text); } finally { if (mounted) setState(() => loading = false); } }
  @override Widget build(BuildContext context) => Scaffold(body: Center(child: Padding(padding: const EdgeInsets.all(24), child: Column(mainAxisSize: MainAxisSize.min, children: [TextField(controller: email, decoration: const InputDecoration(labelText: 'Email')), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password')), const SizedBox(height: 16), ElevatedButton(onPressed: loading ? null : submit, child: Text(loading ? 'Loading...' : 'Login')), TextButton(onPressed: () => context.go('/register'), child: const Text('Register'))]))));
}
class RegisterChoiceScreen extends StatelessWidget { const RegisterChoiceScreen({super.key}); @override Widget build(BuildContext context) => Scaffold(body: Center(child: Column(mainAxisSize: MainAxisSize.min, children: [ElevatedButton(onPressed: () => context.go('/register/customer'), child: const Text('Register Customer')), ElevatedButton(onPressed: () => context.go('/register/provider'), child: const Text('Register Provider'))]))); }
class CustomerRegisterScreen extends ConsumerStatefulWidget { const CustomerRegisterScreen({super.key}); @override ConsumerState<CustomerRegisterScreen> createState() => _CustomerRegisterScreenState(); }
class _CustomerRegisterScreenState extends ConsumerState<CustomerRegisterScreen> { final fullName=TextEditingController(), email=TextEditingController(), phone=TextEditingController(), password=TextEditingController(); bool loading=false; Future<void> submit() async { setState(()=>loading=true); try { await ref.read(authRepositoryProvider).signUpCustomer(fullName: fullName.text.trim(), email: email.text.trim(), phone: phone.text.trim(), password: password.text); } finally { if (mounted) setState(()=>loading=false); } } @override Widget build(BuildContext context)=>Scaffold(appBar: AppBar(title: const Text('Register Customer')), body: ListView(padding: const EdgeInsets.all(24), children:[TextField(controller: fullName, decoration: const InputDecoration(labelText: 'Nama lengkap')), TextField(controller: email, decoration: const InputDecoration(labelText: 'Email')), TextField(controller: phone, decoration: const InputDecoration(labelText: 'Nomor HP')), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password')), const SizedBox(height: 16), ElevatedButton(onPressed: loading ? null : submit, child: const Text('Daftar'))])); }
class ProviderRegisterScreen extends ConsumerStatefulWidget { const ProviderRegisterScreen({super.key}); @override ConsumerState<ProviderRegisterScreen> createState() => _ProviderRegisterScreenState(); }
class _ProviderRegisterScreenState extends ConsumerState<ProviderRegisterScreen> { final fullName=TextEditingController(), email=TextEditingController(), phone=TextEditingController(), password=TextEditingController(), parkingName=TextEditingController(), address=TextEditingController(), capacity=TextEditingController(), latitude=TextEditingController(), longitude=TextEditingController(); File? parkingPhoto; File? ktpPhoto; bool loading=false; Future<void> pickPhoto(bool ktp) async { final picked = await ImagePicker().pickImage(source: ImageSource.gallery); if (picked != null) setState(() => ktp ? ktpPhoto = File(picked.path) : parkingPhoto = File(picked.path)); } Future<void> submit() async { setState(()=>loading=true); try { final repo = ref.read(authRepositoryProvider); await repo.signUpProvider(fullName: fullName.text.trim(), email: email.text.trim(), phone: phone.text.trim(), password: password.text, parkingName: parkingName.text.trim(), address: address.text.trim(), capacity: int.tryParse(capacity.text) ?? 0, latitude: double.tryParse(latitude.text) ?? 0, longitude: double.tryParse(longitude.text) ?? 0, parkingPhotoUrl: parkingPhoto?.path ?? '', ktpPhotoUrl: ktpPhoto?.path ?? ''); } finally { if (mounted) setState(()=>loading=false); } } @override Widget build(BuildContext context)=>Scaffold(appBar: AppBar(title: const Text('Register Provider')), body: ListView(padding: const EdgeInsets.all(24), children:[TextField(controller: fullName, decoration: const InputDecoration(labelText: 'Nama lengkap')), TextField(controller: email, decoration: const InputDecoration(labelText: 'Email')), TextField(controller: phone, decoration: const InputDecoration(labelText: 'Nomor HP')), TextField(controller: password, obscureText: true, decoration: const InputDecoration(labelText: 'Password')), TextField(controller: parkingName, decoration: const InputDecoration(labelText: 'Nama tempat parkir')), TextField(controller: address, decoration: const InputDecoration(labelText: 'Alamat')), TextField(controller: capacity, keyboardType: TextInputType.number, decoration: const InputDecoration(labelText: 'Kapasitas kendaraan')), Row(children:[Expanded(child: TextField(controller: latitude, decoration: const InputDecoration(labelText: 'Latitude'))), const SizedBox(width: 12), Expanded(child: TextField(controller: longitude, decoration: const InputDecoration(labelText: 'Longitude')))]), const SizedBox(height: 12), OutlinedButton(onPressed: () => pickPhoto(false), child: Text(parkingPhoto == null ? 'Upload foto lahan' : 'Foto lahan dipilih')), OutlinedButton(onPressed: () => pickPhoto(true), child: Text(ktpPhoto == null ? 'Upload KTP' : 'KTP dipilih')), const SizedBox(height: 16), ElevatedButton(onPressed: loading ? null : submit, child: const Text('Daftar Provider'))])); }
